import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy — Donow',
};

export default function PrivacyPage() {
  return (
    <div className="bg-gray-50 min-h-screen px-4 py-12">
      <div className="mx-auto max-w-3xl rounded-lg bg-white p-8 shadow">
        <h1 className="mb-2 text-3xl font-bold text-gray-900">Privacy Policy</h1>
        <p className="mb-8 text-sm text-gray-500">Last updated: May 2025</p>

        <section className="mb-6">
          <h2 className="mb-2 text-lg font-bold text-gray-800">1. Introduction</h2>
          <p className="text-sm leading-relaxed text-gray-600">
            Donow (&ldquo;we&rdquo;, &ldquo;our&rdquo;) is committed to protecting your privacy. This Privacy Policy explains
            what information we collect, how we use it, and your rights regarding your data when you
            use the Donow platform.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="mb-2 text-lg font-bold text-gray-800">2. Information We Collect</h2>
          <p className="mb-2 text-sm font-semibold text-gray-700">Account Information</p>
          <ul className="mb-3 list-disc space-y-1 pl-5 text-sm leading-relaxed text-gray-600">
            <li>Name, email address, and phone number provided at signup.</li>
            <li>City, state, and pincode for donation location display.</li>
            <li>Profile photo (optional) uploaded by you.</li>
          </ul>
          <p className="mb-2 text-sm font-semibold text-gray-700">Donation Listings</p>
          <ul className="mb-3 list-disc space-y-1 pl-5 text-sm leading-relaxed text-gray-600">
            <li>Title, description, category, condition, and pickup city of items you list.</li>
            <li>Photos of items uploaded by you (stored on Cloudinary).</li>
          </ul>
          <p className="mb-2 text-sm font-semibold text-gray-700">Usage Data</p>
          <ul className="list-disc space-y-1 pl-5 text-sm leading-relaxed text-gray-600">
            <li>Pages visited and features used (via Firebase Analytics).</li>
            <li>Messages sent through the in-app messaging system.</li>
            <li>Notifications generated by platform activity.</li>
          </ul>
        </section>

        <section className="mb-6">
          <h2 className="mb-2 text-lg font-bold text-gray-800">3. How We Use Your Information</h2>
          <ul className="list-disc space-y-1 pl-5 text-sm leading-relaxed text-gray-600">
            <li>To create and manage your account.</li>
            <li>To display your donation listings to other users.</li>
            <li>To facilitate messaging between donors and recipients.</li>
            <li>To send in-app notifications about activity on your listings.</li>
            <li>To enforce our Terms of Service and keep the platform safe.</li>
            <li>To improve and maintain the Platform.</li>
          </ul>
        </section>

        <section className="mb-6">
          <h2 className="mb-2 text-lg font-bold text-gray-800">4. Information Sharing</h2>
          <p className="text-sm leading-relaxed text-gray-600">
            We do not sell, rent, or trade your personal information to third parties. Your name
            and city are visible to other users when you post a donation or send a message. Your
            email and phone number are not shown publicly. We use the following third-party
            services: Firebase (Google) for authentication and database, and Cloudinary for image
            storage. Each has its own privacy policy governing data processing.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="mb-2 text-lg font-bold text-gray-800">5. Data Retention</h2>
          <p className="text-sm leading-relaxed text-gray-600">
            Your account data is retained as long as your account is active. You may request
            deletion of your account and associated data by contacting us. Donated item listings
            may remain in a completed or archived state for record-keeping.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="mb-2 text-lg font-bold text-gray-800">6. Security</h2>
          <p className="text-sm leading-relaxed text-gray-600">
            We use Firebase&rsquo;s security infrastructure and Firestore security rules to protect your
            data. Authentication is handled via Firebase Auth using email magic links. While we
            take reasonable precautions, no online service is 100% secure and we cannot guarantee
            absolute security.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="mb-2 text-lg font-bold text-gray-800">7. Cookies</h2>
          <p className="text-sm leading-relaxed text-gray-600">
            Donow uses browser local storage to maintain your login session (via Firebase Auth).
            We do not use third-party advertising cookies. Firebase may use cookies for analytics
            and session management.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="mb-2 text-lg font-bold text-gray-800">8. Children&rsquo;s Privacy</h2>
          <p className="text-sm leading-relaxed text-gray-600">
            Donow is not directed at children under 18. We do not knowingly collect personal
            information from minors. If you believe a minor has created an account, please contact
            us and we will delete it promptly.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="mb-2 text-lg font-bold text-gray-800">9. Your Rights</h2>
          <ul className="list-disc space-y-1 pl-5 text-sm leading-relaxed text-gray-600">
            <li>Access the personal data we hold about you.</li>
            <li>Request correction of inaccurate data via your profile settings.</li>
            <li>Request deletion of your account and data.</li>
            <li>Withdraw consent for non-essential data processing.</li>
          </ul>
          <p className="mt-2 text-sm text-gray-600">
            To exercise these rights, contact us at{' '}
            <a href="mailto:support@donow.in" className="text-teal-600 hover:underline">
              support@donow.in
            </a>
            .
          </p>
        </section>

        <section className="mb-8">
          <h2 className="mb-2 text-lg font-bold text-gray-800">10. Changes to This Policy</h2>
          <p className="text-sm leading-relaxed text-gray-600">
            We may update this Privacy Policy periodically. We will notify users of significant
            changes. Continued use of the Platform after changes are posted constitutes acceptance.
          </p>
        </section>

        <div className="mt-6 border-t pt-4 flex gap-4 text-sm">
          <Link href="/terms" className="text-teal-600 hover:underline">Terms of Service</Link>
          <Link href="/" className="text-gray-500 hover:underline">Back to Home</Link>
        </div>
      </div>
    </div>
  );
}
